// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'menu-imprint-label'
  | 'menuitem-intake-label'
  | 'menuitem-mirror-label'
  | 'menuitem-reconcile-label'
  | 'pref-browse'
  | 'pref-crossref-email'
  | 'pref-crossref-hint'
  | 'pref-crossref-title'
  | 'pref-folders-title'
  | 'pref-help'
  | 'pref-mirror-dir'
  | 'pref-mirror-hint'
  | 'pref-source-dir'
  | 'pref-staging-dir'
  | 'pref-title';
